In [10]:
import re
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

In [3]:

df = messages = pd.read_csv("hl7_data_small.csv")

df.head()

Unnamed: 0  Unnamed: 0.1   id  \
0         695           695  696   
1         696           696  697   
2         697           697  698   
3         698           698  699   
4         701           701  702   

                                             message         date_time  \
0  MSH|^~\&|EpiOne_ESP32|Personal_Device|Epione A...  22-09-2021 13:08   
1  MSH|^~\&|EpiOne_ESP32|Personal_Device|Epione A...  22-09-2021 13:08   
2  MSH|^~\&|EpiOne_ESP32|Personal_Device|Epione A...  22-09-2021 13:08   
3  MSH|^~\&|EpiOne_ESP32|Personal_Device|Epione A...  22-09-2021 13:08   
4  MSH|^~\&|EpiOne_ESP32|Personal_Device|Epione A...  22-09-2021 13:08   

   patient_id  ecg  pulse_oximeter  bp  gsr  emg     labels  
0          12    1               1   1    1    1  [1, 1, 1]  
1          12    1               1   1    1    1  [1, 1, 1]  
2          12    1               1   1    1    1  [1, 1, 1]  
3          12    1               1   1    1    1  [1, 1, 1]  
4          12    1               1   1    1    1  [1, 1, 1]

In [4]:
X = df["message"]
y = df["ecg"]

In [ ]:
messages['message'][1]

In [6]:
messages.reset_index(inplace=True)


In [7]:
corpus = []

for i in range(0, len(messages)):
    # print(i)
    review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i])
    review = re.sub(' +', ' ', review)
    review = review.lower()
    corpus.append(review)

print(i)

corpus[0]

791


'msh epione esp32 personal device epione android app personal oru r01 59689 p 2 3 al ne obx 1 nm ecg ecg local ecg ecg sdn 4095 f epionev2 v2 epione obx 2 nm pulse pulse local pulse pulse sdn 57 f epionev2 v2 epione obx 3 nm o2 o2 local o2 o2 sdn 100 f epionev2 v2 epione obx 4 nm temp temperature local temp temperature sdn 81 05 f epionev2 v2 epione obx 5 nm gsr gsr local gsr gsr sdn 1840 f epionev2 v2 epione obx 6 nm emg emg local emg emg sdn 795 f epionev2 v2 epione obx 7 nm bp pulse sys dia pulse local bp pulse sys dia pulse sdn 117 080 057 f epionev2 v2 epione'

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(y_train)
Test_Y = Encoder.fit_transform(y_test)

Train_X = X_train
Test_X = X_test

Train_Y[0:10]

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [11]:
Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(corpus)
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

In [17]:
# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, Test_Y)*100)

Naive Bayes Accuracy Score ->  76.89075630252101


In [16]:
#Corrects some assumptions of Multinomial NB
C_Naive = naive_bayes.ComplementNB()
C_Naive.fit(Train_X_Tfidf,Train_Y)

predictions_CNB = C_Naive.predict(Test_X_Tfidf)

print("Complement Naive Bayes Accuracy Score -> ",accuracy_score(predictions_CNB, Test_Y)*100)

Complement Naive Bayes Accuracy Score ->  83.19327731092437


In [15]:
B_Naive = naive_bayes.BernoulliNB()
B_Naive.fit(Train_X_Tfidf,Train_Y)

predictions_BNB = B_Naive.predict(Test_X_Tfidf)

print("Bernoulli Naive Bayes Accuracy Score -> ",accuracy_score(predictions_BNB, Test_Y)*100)

Bernoulli Naive Bayes Accuracy Score ->  81.09243697478992


In [26]:
G_Naive = naive_bayes.GaussianNB()
G_Naive.fit(Train_X_Tfidf.toarray(),Train_Y)

predictions_GNB = G_Naive.predict(Test_X_Tfidf.toarray())

print("Gaussian Naive Bayes Accuracy Score -> ",accuracy_score(predictions_GNB, Test_Y)*100)


Gaussian Naive Bayes Accuracy Score ->  74.78991596638656


In [13]:
print(predictions_NB[0:10])
print(Test_Y[0:10])

[0 1 0 1 1 0 1 1 1 1]
[0 1 0 1 1 0 1 1 1 0]
